blog_basico/config/routes.rb
BlogBasico::Application.routes.draw do
  get "comentarios/index"
  resources :comentarios

  get "welcome/index" 
  get "posts/reporte" => 'posts#reporte'
  get "posts/comment" => 'posts#comment'
  get "comentarios/index" => "comentarios#index"
  
  post "comentarios/index" => "comentarios#index"

  resources :posts

   root 'welcome#index'

  get ':controller(/:action(/:id(.:format)))'
end

blog_basico/app/models/comentario.rb
class Comentario < ActiveRecord::Base

end

blog_basico/app/models/post.rb
class Post < ActiveRecord::Base
end

blog_basico/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog_basico/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  def index
  	@comentario=params[:comentario_value]
  	#@comentario = Comentario.create({text: @valor})
  	#@comentarios = Comentario.all
  end
end
 

blog_basico/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  $likes = 0
  def index
    @posts = Post.all.order("created_at DESC" )

  end

  def like
   # @comentario = params[:like]
    $likes+=1
    
  end
  def comment
    #@comentario= Comentario.new
    @comentario=params[:nombre_comentario]
    
    #@comentario = params[:nombre_comentario]

  end

  def reporte
     @posts = Post.all.order("created_at DESC" )

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :category, :text)
    end
end


# rails g model Coment texto:string post:reference

blog_basico/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@posts = Post.all
  end
end

blog_basico/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_basico/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

blog_basico/app/helpers/posts_helper.rb
module PostsHelper
end

blog_basico/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog_basico/app/views/comentarios/index.html.erb
<h1>Comentarios#index</h1>
<p>Find me in app/views/comentarios/index.html.erb</p>

<h1>Bienvenido <%= @comentario %> </h1>

<%= form_tag :action => 'index' do %>
	<p>comenetraris</p>
	<%= text_area_tag  'comentario_value', @comentario %>
	<%= submit_tag 'comentar' %>

	
<% end %>

blog_basico/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogBasico</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #71D757" class='container'>
<nav class='navbar'>
	<div class='navbar-inner'>
		<ul class='nav'>
			<li><%= link_to 'Inicio', root_path %></li>
			
			<li><%= link_to 'Administrativa', posts_path %></li>
			<li><%= link_to 'Reporte',posts_reporte_path %></li>
			
		</ul>
	</div>
</nav>

<%= yield %>

</body>
</html>

blog_basico/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog_basico/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog_basico/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table border=2>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cegory</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.category %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Post', new_post_path %>

blog_basico/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog_basico/app/views/posts/reporte.erb
<h1>hola desde REPORTE</h1>

blog_basico/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
<p>
  <strong>CATEGORIA:</strong>
  <%= @post.category %>
</p>
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<section>
	<p><%= @comentario %></p>
</section>
<div>
	
	<form action="" method="post" >
		
		COMENTARIO::
		<%= text_area_tag 'nombre_comentario', @name %>
		<%= submit_tag "comentar" %>
	</form>
	
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

blog_basico/app/views/welcome/index.html.erb
<h1>Bienbenido a mi Blog Basico :D</h1>

<h2>Listing posts PRINCIPAL</h2>
<ul>
	<% @posts.each do |post| %>
		<li>
			<h3><%= post.title %></h3>
			<h6><%= post.text %></h6>
			
			<h6><%= link_to 'Me Gusta '  %>:: <%= $likes %><h6>

			<%= link_to 'Show', post %>
			
			<%= post.created_at %><!-- ponemos la fecha -->
		</li>
	<%end%>
</ul>
<%= link_to 'New Post', new_post_path %>